version: "3.3"

services:
  restic:
    build: 
      context: ./restic
    image: restic
    container_name: WB-restic
    depends_on: 
      - WB-promtail
    restart: always
    environment:
      TZ: Europe/Warsaw
      RESTIC_REPOSITORY: b2:weaknet-test:/weaknet-test
      RESTIC_BACKUP_SOURCES: /mnt/volumes
      RESTIC_BACKUP_TAGS: docker-volumes
      RESTIC_FORGET_ARGS: --prune --keep-last 14 --keep-daily 1
    env_file:
        - b2credentials.env
    volumes:
        - ./restic/backup.sh:/restic/backup.sh:ro
        - BackupLogs:/var/log/restic
    entrypoint: tail -f /dev/null
    networks:
      - net

  WB-promtail:
    image: grafana/promtail:master
    container_name: WB-promtail
    restart: always
    volumes:
      - BackupLogs:/var/log/restic
      - ./promtail/docker-config.yaml:/etc/promtail/docker-config.yaml
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - net

volumes:
  BackupLogs:

networks:
  net:
    external:
      name: weakmonitor_net

