version: "3.3"

services:
  restic:
    build: 
      context: ./restic
    image: restic
    container_name: WB-restic
    environment:
      TZ: Europe/Warsaw
      RESTIC_REPOSITORY: b2:weaknet-test:/weaknet-test
      RESTIC_BACKUP_SOURCES: /mnt/volumes
      RESTIC_BACKUP_TAGS: docker-volumes
      RESTIC_FORGET_ARGS: --prune --keep-last 14 --keep-daily 1
    env_file:
        - b2credentials.env
    volumes:
        # - /root/zdjecia:/mnt/backup/zdjecia:ro
        - ./restic/entrypoint:/restic/entrypoint:ro
        - ./restic/backup:/restic/backup:ro
        - ./promtail/docker-config.yaml:/etc/promtail/docker-config.yaml
        - BackupLogs:/var/log/restic
    entrypoint: bash /restic/entrypoint
    networks:
      - backup-net
  
  ofelia:
    image: mcuadros/ofelia:latest
    container_name: WB-ofelia
    volumes:
      - ./ofelia/config.ini:/etc/ofelia/config.ini
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backup-net
  
  promtail:
    image: grafana/promtail:master
    container_name: WB-promtail
    volumes:
      - BackupLogs:/var/log/restic
      - ./promtail/docker-config.yaml:/etc/promtail/docker-config.yaml
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - backup-net

volumes:
  BackupLogs:

networks:
  backup-net:
