version: "3.3"

services:
  restic:
    build: 
      context: ./restic
    image: restic
    environment:
      TZ: Europe/Warsaw
      RESTIC_REPOSITORY: b2:weaknet-test:/weaknet-test
      RESTIC_BACKUP_SOURCES: /mnt/volumes
      RESTIC_BACKUP_TAGS: docker-volumes
      RESTIC_FORGET_ARGS: '--prune\ --keep-last\ 14\ --keep-daily\ 1'
    env_file:
        - b2credentials.env
    volumes:
        - /root/zdjecia:/mnt/backup/zdjecia:ro
        - ./restic/entrypoint:/restic/entrypoint:ro
        - ./restic/backup:/restic/backup:ro
    entrypoint: bash /restic/entrypoint
    networks:
      - backup-net
  
  ofelia:
    image: mcuadros/ofelia:latest
    volumes:
      - ./ofelia/config.ini:/etc/ofelia/config.ini
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backup-net

  cadvisor:
    image: google/cadvisor:latest
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - backup-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    #   - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      # - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    # links:
    #   - cadvisor:cadvisor
    #   - alertmanager:alertmanager
    depends_on:
      - cadvisor
      - node-exporter
    networks:
      - backup-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/provisioning/datasources/prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./grafana/provisioning/dashboards/all.yaml:/etc/grafana/provisioning/dashboards/all.yaml
    depends_on:
      - prometheus
    networks:
      - backup-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - backup-net

networks:
  backup-net:
