#!/bin/sh

backupLogFile="/var/log/restic/backup.log"

printAndLog() {
  echo `date "+%T %F"` "${1}" 2>&1 | tee -a ${backupLogFile}
}

printAndLog "Starting container ..."

restic snapshots &>/dev/null
status=$?
printAndLog "Check Repo status $status"

if [ $status != 0 ]; then
    printAndLog "Restic repository '${RESTIC_REPOSITORY}' does not exists. Running restic init."
    restic init 2>&1 | tee -a ${backupLogFile}

    init_status=$?
    printAndLog "Repo init status $init_status"

    if [ $init_status != 0 ]; then
        printAndLog "Failed to init the repository: '${RESTIC_REPOSITORY}'"
        exit 1
    fi
else
    printAndLog "Repository exists"
fi

printAndLog "Container started."

tail -f /dev/null