#!/bin/sh

backupLogFile="/var/log/backup.log"

printAndLog() {
  echo `date "+%T %F"` "${1}" 2>&1 | tee -a ${backupLogFile}
}

printAndLog "`date "+%T %F"` Starting container ..."

restic snapshots &>/dev/null
status=$?
printAndLog "`date "+%T %F"` Check Repo status $status"

if [ $status != 0 ]; then
    printAndLog "`date "+%T %F"` Restic repository '${RESTIC_REPOSITORY}' does not exists. Running restic init."
    restic init 2>&1 | tee -a ${backupLogFile}

    init_status=$?
    printAndLog "`date "+%T %F"` Repo init status $init_status"

    if [ $init_status != 0 ]; then
        printAndLog "`date "+%T %F"` Failed to init the repository: '${RESTIC_REPOSITORY}'"
        exit 1
    fi
else
    printAndLog "`date "+%T %F"` Repository exists"
fi

printAndLog "`date "+%T %F"` Setup backup cron job with cron expression BACKUP_CRON: ${BACKUP_CRON}"
echo "${BACKUP_CRON} /bin/sh /restic/backup 2>&1" >> /var/spool/cron/crontabs/root
echo "#" >> /var/spool/cron/crontabs/root

printAndLog "`date "+%T %F"` Container started."

service cron start

tail -f /dev/null