server:

  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/api/prom/push

scrape_configs:
  - job_name: restic
    static_configs:
    - targets:
        - localhost
      labels:
        job: weakbackup
        __path__: /var/log/restic/backup.log
